### ISSUE TITLE
Question [why is it free]

### ISSUE THREAD

**Issue by FoksVHox** [ExtReMLapin/BadCoderz#7]
Why did you upload Bad Coderz to Github? I know this isn't an issue, but I kinda feel that I've been scammed.

**Comment by ExtReMLapin** [comment]
You didn't get scammed as you got what you paid for and you had free & premium support on gmodstore.

Scamming is paying for something and not getting it.

Since i'm working for my government since the 31 of December 2019 I'm not legally allowed to have another job.

There are others reasons that led me to do so but it's not the right place to discuss about it.

Also open-sourcing badcoderz allowed to fix a security issue.


Also everyone who purchased it is credited in the "credits" menu animation.

Hover the bottom left of the menu to reveal the hidden button and click to start the small animation :)

However, I understand it can be frustrating.

But think about it, since it's open-sourced the soft DRM got removed and you can now use it with any steamid.

**Comment by FoksVHox** [comment]
I know I didn't get scammed but I just wanted to hear what the reason was to open-source BadCoderz. Also, I'm glad that you understand my frustration.

That law sounds like some bs to me.
